name: Build & Deploy ConfigManagerApp UI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_WATER_0B475E70F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
         
          
          app_location: "./UI/config-manager-app" 
          api_location: "" 
          output_location: "dist" 
          app_build_command: 'npm run build --mode=production'